# hugo server -b vscode.homelab.cake.sh --bind 0.0.0.0

baseURL = "https://blog.cake.sh/"
languageCode = "en-us"
title = "Cake Labs"
theme = "m10c"

[permalinks]
  posts = "/:year/:month/:title/"

[params]
  author = "Cake"
  description = "All Things Technical / Twitch / Infosec / Sysadmin in Recovery."
  avatar = "/global/avatar.png"
  [[params.social]]
    name = "github"
    url = "https://github.com/ILiedAboutCake"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/ILiedAboutCake"