name: Build and Deploy

on:
    push:
      branches:
      - master

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Checkout Theme
        uses: actions/checkout@v2
        with:
          repository: vaga/hugo-theme-m10c
          path: themes/m10c
      - name: Install Hugo
        run: |
          HUGO_DOWNLOAD=hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
          wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/${HUGO_DOWNLOAD}
          tar xvzf ${HUGO_DOWNLOAD} hugo
          mv hugo $HOME/hugo
        env:
          HUGO_VERSION: 0.75.1
      - name: Hugo Build
        run: $HOME/hugo -v
      - name: Deploy to prod
        uses: appleboy/scp-action@master
        with: 
          host: ${{ secrets.SCP_HOST }}
          username: ${{ secrets.SCP_USERNAME }}
          port: "22"
          key: ${{ secrets.SCP_KEY }}
          source: "public/*"
          target: ${{ secrets.SCP_TARGET }}
          strip_components: 1
